package com.cnc.mybatis.generator.dao;

import com.cnc.mybatis.generator.dataObject.UserSecretInfoDO;

public interface UserSecretInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_secret_info
     *
     * @mbggenerated Sat Nov 13 16:30:09 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_secret_info
     *
     * @mbggenerated Sat Nov 13 16:30:09 CST 2021
     */
    int insert(UserSecretInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_secret_info
     *
     * @mbggenerated Sat Nov 13 16:30:09 CST 2021
     */
    int insertSelective(UserSecretInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_secret_info
     *
     * @mbggenerated Sat Nov 13 16:30:09 CST 2021
     */
    UserSecretInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_secret_info
     *
     * @mbggenerated Sat Nov 13 16:30:09 CST 2021
     */
    int updateByPrimaryKeySelective(UserSecretInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_secret_info
     *
     * @mbggenerated Sat Nov 13 16:30:09 CST 2021
     */
    int updateByPrimaryKey(UserSecretInfoDO record);
}