package com.cnc.fp.account.dao;

import com.cnc.fp.account.dao.dataObject.UserInfoDO;
import org.springframework.stereotype.Repository;

@Repository
public interface UserInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    int insert(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    int insertSelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    UserInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    int updateByPrimaryKeySelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    int updateByPrimaryKey(UserInfoDO record);
}