package com.cnc.fp.account.dao.dataObject;

import java.util.Date;

public class UserInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Short age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.reg_mode
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Byte regMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.third_party_user_id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private String thirdPartyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.is_deleted
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.add_dt
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Date addDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_dt
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.reg_mode
     *
     * @return the value of user_info.reg_mode
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Byte getRegMode() {
        return regMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.reg_mode
     *
     * @param regMode the value for user_info.reg_mode
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setRegMode(Byte regMode) {
        this.regMode = regMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.third_party_user_id
     *
     * @return the value of user_info.third_party_user_id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public String getThirdPartyUserId() {
        return thirdPartyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.third_party_user_id
     *
     * @param thirdPartyUserId the value for user_info.third_party_user_id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setThirdPartyUserId(String thirdPartyUserId) {
        this.thirdPartyUserId = thirdPartyUserId == null ? null : thirdPartyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.is_deleted
     *
     * @return the value of user_info.is_deleted
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.is_deleted
     *
     * @param isDeleted the value for user_info.is_deleted
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.add_dt
     *
     * @return the value of user_info.add_dt
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Date getAddDt() {
        return addDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.add_dt
     *
     * @param addDt the value for user_info.add_dt
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setAddDt(Date addDt) {
        this.addDt = addDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_dt
     *
     * @return the value of user_info.update_dt
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_dt
     *
     * @param updateDt the value for user_info.update_dt
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}