package com.cnc.fp.account.dao.dataObject;

public class UserSecretInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_secret_info.id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_secret_info.user_id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_secret_info.encrypt_password
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    private String encryptPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_secret_info.id
     *
     * @return the value of user_secret_info.id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_secret_info.id
     *
     * @param id the value for user_secret_info.id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_secret_info.user_id
     *
     * @return the value of user_secret_info.user_id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_secret_info.user_id
     *
     * @param userId the value for user_secret_info.user_id
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_secret_info.encrypt_password
     *
     * @return the value of user_secret_info.encrypt_password
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public String getEncryptPassword() {
        return encryptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_secret_info.encrypt_password
     *
     * @param encryptPassword the value for user_secret_info.encrypt_password
     *
     * @mbggenerated Mon Nov 15 10:56:53 CST 2021
     */
    public void setEncryptPassword(String encryptPassword) {
        this.encryptPassword = encryptPassword;
    }
}